namespace SpriteKind {
    export const Entity = SpriteKind.create()
    export const Entity2 = SpriteKind.create()
    export const F_Entity = SpriteKind.create()
}
sprites.onOverlap(SpriteKind.Player, SpriteKind.Entity2, function (sprite, otherSprite) {
    sprites.destroy(otherSprite, effects.ashes, 100)
    tiles.setCurrentTilemap(tilemap`level7`)
    FamiliarEntity = sprites.create(img`
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . e e e e e e . . . . . 
        . . . . e e e e e e e e . . . . 
        . . . e e e e e e e e e e . . . 
        . . . e e e d d d d e e e . . . 
        . . . e d b f d d f b d e . . . 
        . . e e d 1 f d d f 1 d e e . . 
        . . e e d d d d d d d d e e . . 
        . e e f d d d d d d d d f e e . 
        . e 8 8 f 8 8 8 8 8 8 f 8 8 e . 
        . . 8 8 f 8 8 8 8 8 8 f 8 8 . . 
        . . 8 8 f 8 8 8 8 8 8 f 8 8 . . 
        . . d d . f f f f f f . d d . . 
        . . . . . f f . . f f . . . . . 
        `, SpriteKind.F_Entity)
    tiles.placeOnTile(FamiliarEntity, tiles.getTileLocation(7, 3))
    tiles.placeOnTile(Eli, tiles.getTileLocation(7, 6))
    controller.moveSprite(Eli, 1, 1)
    timer.after(3500, function () {
        animation.runImageAnimation(
        FamiliarEntity,
        [img`
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . e e e e e e . . . . . 
            . . . . e e e e e e e e . . . . 
            . . . e e e e e e e e e e . . . 
            . . . e e e d d d d e e e . . . 
            . . . e d b f d d f b d e . . . 
            . . e e d 1 f d d f 1 d e e . . 
            . . e e d d d d d d d d e e . . 
            . e e e d d d d d d d d e e e . 
            . e 8 8 f 8 8 8 8 8 8 f 8 8 e . 
            . . 8 8 f 8 8 8 8 8 8 f 8 8 . . 
            . . 8 8 f 8 8 8 8 8 8 f 8 8 . . 
            . . d d . f f f f f f . d d . . 
            . . . . . f f . . f f . . . . . 
            `,img`
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . e e e e e e . . . . . 
            . . . . e e e e e e e e . . . . 
            . . . e e e e e e e e e e . . . 
            . . . e e e d d d d e e e . . . 
            . . . e d 1 1 d d 1 1 d e . . . 
            . . e e d 1 1 d d 1 1 d e e . . 
            . . e e d 2 d d d d 2 d e e . . 
            . e e e d d d d d d d d e e e . 
            . e 8 8 f 8 8 8 8 8 8 f 8 8 e . 
            . . 8 8 f 8 8 8 8 8 8 f 8 8 . . 
            . . 8 8 f 8 8 8 8 8 8 f 8 8 . . 
            . . d d . f f f f f f . d d . . 
            . . . . . f f . . f f . . . . . 
            `,img`
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . e e e e e e . . . . . 
            . . . . e e e e e e e e . . . . 
            . . . e e e e e e e e e e . . . 
            . . . e e e d d d d e e e . . . 
            . . . e d 1 1 d d 1 1 d e . . . 
            . . e e d 1 1 d d 1 1 d e e . . 
            . . e e d 2 d d d d 2 d e e . . 
            . e e e d 2 d d d d 2 d e e e . 
            . e f f f 8 8 8 8 8 8 f f f e . 
            . . f f f 8 8 8 8 8 8 f f f . . 
            . . f f f 8 8 8 8 8 8 f f f . . 
            . . f f . f f f f f f . f f . . 
            . . . . . f f . . f f . . . . . 
            `,img`
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . e e e e e e . . . . . 
            . . . . e e e e e e e e . . . . 
            . . . e e e e e e e e e e . . . 
            . . . e f f f f f f f f e . . . 
            . . . e f 1 1 f f 1 1 f e . . . 
            . . e e f 1 1 f f 1 1 f e e . . 
            . . e e f 2 f f f f 2 f e e . . 
            . e e e f 2 f f f f 2 f e e e . 
            . e f f f f f f f f f f f f e . 
            . . f f f f f f f f f f f f . . 
            . . f f f f f f f f f f f f . . 
            . . f f . f f f f f f . f f . . 
            . . . . . f f . . f f . . . . . 
            `,img`
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . f f f f f f f f . . . . 
            . . . f f f f f f f f f f . . . 
            . . . f f f f f f f f f f . . . 
            . . . f f 1 1 f f 1 1 f f . . . 
            . . . f f 1 1 f f 1 1 f f . . . 
            . . . f f 2 f f f f 2 f f . . . 
            . . . . f 2 f f f f 2 f . . . . 
            . . f f f f f f f f f f f f . . 
            . . f f f f f f f f f f f f . . 
            . . f f f f f f f f f f f f . . 
            . . f f . f f f f f f . f f . . 
            . . . . . f f . . f f . . . . . 
            `],
        2000,
        false
        )
    })
})
controller.up.onEvent(ControllerButtonEvent.Pressed, function () {
    if (HumanMove == 1) {
        animation.runImageAnimation(
        Eli,
        [img`
            . . . . . . f f f f . . . . . . 
            . . . . f f e e e e f f . . . . 
            . . . f e e e f f e e e f . . . 
            . . f f f f f 2 2 f f f f f . . 
            . . f f e 2 e 2 2 e 2 e f f . . 
            . . f e 2 f 2 f f 2 f 2 e f . . 
            . . f f f 2 2 e e 2 2 f f f . . 
            . f f e f 2 f e e f 2 f e f f . 
            . f e e f f e e e e f e e e f . 
            . . f e e e e e e e e e e f . . 
            . . . f e e e e e e e e f . . . 
            . . e 4 f f f f f f f f 4 e . . 
            . . 4 d f 2 2 2 2 2 2 f d 4 . . 
            . . 4 4 f 4 4 4 4 4 4 f 4 4 . . 
            . . . . . f f f f f f . . . . . 
            . . . . . f f . . f f . . . . . 
            `,img`
            . . . . . . . . . . . . . . . . 
            . . . . . . f f f f . . . . . . 
            . . . . f f e e e e f f . . . . 
            . . . f e e e f f e e e f . . . 
            . . . f f f f 2 2 f f f f . . . 
            . . f f e 2 e 2 2 e 2 e f f . . 
            . . f e 2 f 2 f f f 2 f e f . . 
            . . f f f 2 f e e 2 2 f f f . . 
            . . f e 2 f f e e 2 f e e f . . 
            . f f e f f e e e f e e e f f . 
            . f f e e e e e e e e e e f f . 
            . . . f e e e e e e e e f . . . 
            . . . e f f f f f f f f 4 e . . 
            . . . 4 f 2 2 2 2 2 e d d 4 . . 
            . . . e f f f f f f e e 4 . . . 
            . . . . f f f . . . . . . . . . 
            `,img`
            . . . . . . f f f f . . . . . . 
            . . . . f f e e e e f f . . . . 
            . . . f e e e f f e e e f . . . 
            . . f f f f f 2 2 f f f f f . . 
            . . f f e 2 e 2 2 e 2 e f f . . 
            . . f e 2 f 2 f f 2 f 2 e f . . 
            . . f f f 2 2 e e 2 2 f f f . . 
            . f f e f 2 f e e f 2 f e f f . 
            . f e e f f e e e e f e e e f . 
            . . f e e e e e e e e e e f . . 
            . . . f e e e e e e e e f . . . 
            . . e 4 f f f f f f f f 4 e . . 
            . . 4 d f 2 2 2 2 2 2 f d 4 . . 
            . . 4 4 f 4 4 4 4 4 4 f 4 4 . . 
            . . . . . f f f f f f . . . . . 
            . . . . . f f . . f f . . . . . 
            `,img`
            . . . . . . . . . . . . . . . . 
            . . . . . . f f f f . . . . . . 
            . . . . f f e e e e f f . . . . 
            . . . f e e e f f e e e f . . . 
            . . . f f f f 2 2 f f f f . . . 
            . . f f e 2 e 2 2 e 2 e f f . . 
            . . f e f 2 f f f 2 f 2 e f . . 
            . . f f f 2 2 e e f 2 f f f . . 
            . . f e e f 2 e e f f 2 e f . . 
            . f f e e e f e e e f f e f f . 
            . f f e e e e e e e e e e f f . 
            . . . f e e e e e e e e f . . . 
            . . e 4 f f f f f f f f e . . . 
            . . 4 d d e 2 2 2 2 2 f 4 . . . 
            . . . 4 e e f f f f f f e . . . 
            . . . . . . . . . f f f . . . . 
            `],
        100,
        true
        )
        Direction1 = 0
    }
    if (HumanMove == 2) {
        animation.runImageAnimation(
        Eli,
        [img`
            ........................
            ........................
            ........................
            ........................
            ..........ffff..........
            ........ff1111ff........
            .......fb111111bf.......
            .......f11111111f.......
            ......fd11111111df......
            ......fd11111111df......
            ......fdd111111ddf......
            ......fbd111111dbf......
            ......fcd111111dcf......
            .......fb111111bf.......
            .....bfbfcdb1bdfbfb.....
            ....fcb1bcbfbfcb1bcf....
            ....f11111ffff11111f....
            .....ffffffffffffff.....
            .........ffffff.........
            ...........fff..........
            ........................
            ........................
            ........................
            ........................
            `,img`
            ........................
            ........................
            ........................
            ........................
            ..........ffff..........
            ........ff1111ff........
            .......fb111111bf.......
            .......f11111111f.......
            ......fd11111111df......
            ......fd11111111df......
            ......fdd111111ddf......
            ......fbd111111dbf......
            ......fcd111111dcf......
            .......fb111111fbfb.....
            .....bfbfcdb1bcb1bcf....
            ....fcb1bcbfbf11111f....
            ....f11111ffffbffff.....
            .....ffffffffff.........
            .........fffff..........
            ..........fff...........
            ........................
            ........................
            ........................
            ........................
            `,img`
            ........................
            ........................
            ........................
            ........................
            ..........ffff..........
            ........ff1111ff........
            .......fb111111bf.......
            .......f11111111f.......
            ......fd11111111df......
            ......fd11111111df......
            ......fdd111111ddf......
            ......fbd111111dbf......
            ......fcd111111dcf......
            .......fb111111bf.......
            .....bfbfcdb1bdfbfb.....
            ....fcb1bcbfbfcb1bcf....
            ....f11111ffff11111f....
            .....ffffffffffffff.....
            .........ffffff.........
            ...........fff..........
            ........................
            ........................
            ........................
            ........................
            `,img`
            ........................
            ........................
            ........................
            ........................
            ..........ffff..........
            ........ff1111ff........
            .......fb111111bf.......
            .......f11111111f.......
            ......fd11111111df......
            ......fd11111111df......
            ......fdd111111ddf......
            ......fbd111111dbf......
            ......fcd111111dcf......
            .....bfbf111111bf.......
            ....fcb1bcdb1bdfbfb.....
            ....f111bcbfbfcb1bcf....
            .....ffffbffff11111f....
            .........ffffffffff.....
            ..........fffff.........
            ...........fff..........
            ........................
            ........................
            ........................
            ........................
            `],
        100,
        true
        )
        Direction1 = 4
    }
})
controller.A.onEvent(ControllerButtonEvent.Pressed, function () {
    if (ScratchAttack == 1) {
        if (can_attack == 0) {
            if (controller.down.isPressed()) {
                animation.runImageAnimation(
                Eli,
                [img`
                    ........................
                    ........................
                    ........................
                    ........................
                    ........................
                    ..........ffff..........
                    ........ff1111ff........
                    .......fb111111bf.......
                    .....fffc1111111f.......
                    ...fc111cd1111111f......
                    ...f1b1b1b1111dddf......
                    ...fbfbffcf11fcddf......
                    ......fcf111111bbf......
                    .......ccbdb1b1fcf......
                    .......fffbfbfdff.......
                    ........ffffffff........
                    ........fffffffffff.....
                    .........fffffc111cf....
                    .........fffff1b1b1f....
                    ..........ffffbfbfbf....
                    ...........ffff.........
                    ........................
                    ........................
                    ........................
                    `,img`
                    ........................
                    ........................
                    ........................
                    ........................
                    ........................
                    ..........ffff..........
                    ........ff1111ff........
                    .......fb111111bf.......
                    .......f11111111f.......
                    ......fd11111111df......
                    ...44.fd11111111df......
                    ..44..fd11111111df......
                    ..44..fd11111111df......
                    ..44..fddd1111dddff.....
                    ..444.fbdbfddfbdbfcf....
                    ..4444fcdcf11fcdcfbf....
                    ...444fffbdb1bdffcf.....
                    ....fcb1bcffffff........
                    ....f1c1c1ffffff........
                    ....fdfdfdfffff.........
                    .....f.f.f..............
                    ........................
                    ........................
                    ........................
                    `,img`
                    ........................
                    ........................
                    ........................
                    ........................
                    ..........ffff..........
                    ........ff1111ff........
                    .......fb111111bf.......
                    .......f11111111f.......
                    ......fd111111111f......
                    ......fd11111111df......
                    ...44.fd11111111df......
                    ..444.fcdd1111ddcff.....
                    ..44...fbcf11fcbfbbf....
                    ..44...ffbdb1bdffff.....
                    ..444...fcbfbfdf........
                    ..4444..ffffffff........
                    ...444ffffffffff........
                    .....fcb1bcffff.........
                    ......ffbff.............
                    ........................
                    ........................
                    ........................
                    ........................
                    ........................
                    `,img`
                    ........................
                    ........................
                    ........................
                    ........................
                    ..........ffff..........
                    ........ff1111ff........
                    .......fb111111bf.......
                    .......f11111111f.......
                    ......fd11111111df......
                    ......fdd111111ddf......
                    ......fbdd1111dddf......
                    ......fcdbfddfbdbf......
                    .......fbcf11fcbfff.....
                    .......ffb1111bcfbcf....
                    ........fcdb1bdfbbbf....
                    .......ffffffffffcf.....
                    .....fcb1bcfffff........
                    .....f1b1b1ffff.........
                    ......ffbff.............
                    ........................
                    ........................
                    ........................
                    ........................
                    ........................
                    `],
                100,
                false
                )
                can_attack = 1
                timer.after(400, function () {
                    can_attack = 0
                })
            }
            if (controller.up.isPressed()) {
                animation.runImageAnimation(
                Eli,
                [img`
                    ........................
                    ........................
                    ........................
                    ........................
                    ........................
                    .........ffffff.........
                    .......ff111111ff.......
                    .......f11111111f.......
                    ......fd11111111df......
                    ......fd11111111df......
                    ......fdd111111ddf......
                    ......fbd111111dbf......
                    ......fcd111111dcf......
                    .......fb111111bfcbb....
                    ......cbfcdb1bdfcb1f....
                    .....bc1bcbfbfcb111f....
                    ....f11111ffff111ff.....
                    ....f11ffffffffff.......
                    .....ff..ffffff.........
                    ...........fff..........
                    ........................
                    ........................
                    ........................
                    ........................
                    `,img`
                    ........................
                    ........................
                    ........................
                    ........................
                    ........................
                    .........ffffff.........
                    .......ff111111ff.......
                    .......f11111111f.......
                    ......f11dd11dd11f......
                    ......f1dd1111dddf...44.
                    ......fdd111111ddf..4444
                    ......fbd111111dbf.44444
                    ......fcd111111dcf4444..
                    .......fb111111bfcb44...
                    ......cbfcdb1bdfcb1f....
                    .....bc1bcbfbfcb111f....
                    ....f11111ffff111ff.....
                    ....f11ffffffffff.......
                    .....ff.ffffff..........
                    ..........ff............
                    ........................
                    ........................
                    ........................
                    ........................
                    `,img`
                    ........................
                    ........................
                    ........................
                    ........................
                    ........................
                    .........ffffff.........
                    .......ff111111ff.......
                    .......f11111111f...444.
                    ......f111111111df..444.
                    ......f111111d11df.444..
                    ......fddddd1ddddf.444..
                    ......fbdd1111ddbf4444..
                    ......fcd111111dcf44....
                    .......fb111111bf444....
                    ......cbfcdb1bdfcf1f....
                    .....bc1bcbfbfcb111f....
                    ....f11111ffff1111f.....
                    ....f11fffffffffff......
                    .....ff..ffffff.........
                    ...........fff..........
                    ........................
                    ........................
                    ........................
                    ........................
                    `,img`
                    ........................
                    ........................
                    ........................
                    ........................
                    ........................
                    ........ffffffff........
                    .......fb111111bf.......
                    .......f11111111f.......
                    ......f11d111dd11f......
                    ......f11d1111d11f......
                    ......fddd11111ddf......
                    ......fbd111111dbf......
                    ......fcd111111dcf......
                    .......fb111111bfbcb....
                    ......cbfcdb1bdfcc1f....
                    .....bc1bcbfbfcb111f....
                    ....f11111ffff11111f....
                    ....f11ffffffffffff.....
                    .....ff..ffffff.........
                    ...........fff..........
                    ........................
                    ........................
                    ........................
                    ........................
                    `],
                100,
                false
                )
                can_attack = 1
                timer.after(400, function () {
                    can_attack = 0
                })
            }
            if (controller.left.isPressed()) {
                animation.runImageAnimation(
                Eli,
                [img`
                    ........................
                    ........................
                    ........................
                    ........................
                    ..........ffff..........
                    ........ff1111ff........
                    .......fb111111bf.......
                    .......f1111111df.......
                    ......fd1111111ddf......
                    ......fd111111dddf......
                    ......fd111ddddddf......
                    ......fd1dfbddddbf......
                    ......fbddfcdbbbcf......
                    .......f11111bbcf.......
                    .......f1b1fffff........
                    .......fbfc111bf........
                    ........ff1b1bff........
                    .........fbfbfff.f......
                    ..........ffffffff......
                    ............fffff.......
                    ........................
                    ........................
                    ........................
                    ........................
                    `,img`
                    ........................
                    ........................
                    ........................
                    ........................
                    .........fffff..........
                    ........f11111ff........
                    ..4....fb111111bf.......
                    .444...f1111111dbf......
                    .4444.fd111111dddf......
                    .4444.fd11111ddddf......
                    ..4444fd11dddddddf......
                    ...444f111dddddddf......
                    ...444f11fcddddddf......
                    ....4fb1111bdddbf.......
                    ....4f1b1bdfcfff........
                    .....fbfbffffffff.......
                    ......fffffffffff.ff....
                    ...........ffffffff.....
                    ........f1b1bffffff.....
                    ........fbfbffffff......
                    ........................
                    ........................
                    ........................
                    ........................
                    `,img`
                    ........................
                    ........................
                    ........................
                    ........................
                    ........................
                    .....444.fffffff........
                    ....444.f111111ff.......
                    ...444.f1111111dbf......
                    ..444.fd1111111ddf......
                    ..444.fd1111111ddf......
                    .4444.fdbc1111dddf......
                    .444..f1ff111ddddf......
                    .444..f1111ddddddf......
                    .44....ffc1bdddbf.......
                    .44cfb..fbdfcfff........
                    ..f1b1bffffffffff.......
                    ..cb1bff..fffffff.ff....
                    ...fff.....ffffffff.....
                    ........f1b1bffffff.....
                    ........fbfbffffff......
                    ........................
                    ........................
                    ........................
                    ........................
                    `,img`
                    ........................
                    ........................
                    ........................
                    ........................
                    ........................
                    .........fffffff........
                    ........f111111ff.......
                    .......f1111111dbf......
                    ......fd1111111ddf......
                    ......fd1111111ddf......
                    ......fdbc1111dddf......
                    ......f1ff111ddddf......
                    ......f1111ddddddf......
                    .......ffc1bdddbf.......
                    ........fbdfcfff........
                    ...ccf.ffffffffff.......
                    ..b1b1cf..fffffff.ff....
                    ..fb1bf....ffffffff.....
                    ...fff..f1b1bffffff.....
                    ........fbfbffffff......
                    ........................
                    ........................
                    ........................
                    ........................
                    `],
                100,
                false
                )
                can_attack = 1
                timer.after(400, function () {
                    can_attack = 0
                })
            }
            if (controller.right.isPressed()) {
                animation.runImageAnimation(
                Eli,
                [img`
                    ........................
                    ........................
                    ........................
                    ........................
                    ..........ffff..........
                    ........ff1111ff........
                    .......fb111111bf.......
                    .......fd1111111f.......
                    ......fdd1111111df......
                    ......fddd111111df......
                    ......fdddddd111df......
                    ......fbddddbfd1df......
                    ......fcbbbdcfddbf......
                    .......fcbb11111f.......
                    ........fffff1b1f.......
                    ........fb111cfbf.......
                    ........ffb1b1ff........
                    ......f.fffbfbf.........
                    ......ffffffff..........
                    .......fffff............
                    ........................
                    ........................
                    ........................
                    ........................
                    `,img`
                    ........................
                    ........................
                    ........................
                    ........................
                    ..........fffff.........
                    ........ff11111f........
                    .......fb111111bf....4..
                    ......fbd1111111f...444.
                    ......fddd111111df.4444.
                    ......fdddd11111df.4444.
                    ......fddddd1cf1df4444..
                    ......fddddddbf11f444...
                    ......fdddddd1111f444...
                    .......fbdddb1fffbf4....
                    ........fffcfff1b1f4....
                    .......ffffffffbfbf.....
                    ....ff.fffffffffff......
                    .....ffffffff...........
                    .....ffffffb1b1f........
                    ......ffffffbfbf........
                    ........................
                    ........................
                    ........................
                    ........................
                    `,img`
                    ........................
                    ........................
                    ........................
                    ........................
                    ........................
                    ........fffffff.444.....
                    .......ff111111f.444....
                    ......fbd1111111f.444...
                    ......fdd1111111df.444..
                    ......fdd1111111df.444..
                    ......fddd1111cbdf.4444.
                    ......fdddd111ff1f..444.
                    ......fdddddd1111f..444.
                    .......fbdddb1cff....44.
                    ........fffcfdbf..bfc44.
                    .......ffffffffffb1b1f..
                    ....ff.fffffff..ffb1bc..
                    .....ffffffff.....fff...
                    .....ffffffb1b1f........
                    ......ffffffbfbf........
                    ........................
                    ........................
                    ........................
                    ........................
                    `,img`
                    ........................
                    ........................
                    ........................
                    ........................
                    ........................
                    ........fffffff.........
                    .......ff111111f........
                    ......fbd1111111f.......
                    ......fdd1111111df......
                    ......fdd1111111df......
                    ......fddd1111cbdf......
                    ......fdddd111ff1f......
                    ......fdddddd1111f......
                    .......fbdddb1cff.......
                    ........fffcfdbf........
                    .......ffffffffff.fcc...
                    ....ff.fffffff..fc1b1b..
                    .....ffffffff....fb1bf..
                    .....ffffffb1b1f..fff...
                    ......ffffffbfbf........
                    ........................
                    ........................
                    ........................
                    ........................
                    `],
                100,
                false
                )
                can_attack = 1
                timer.after(400, function () {
                    can_attack = 0
                })
            }
        }
    }
})
function Animation () {
    moving = controller.left.isPressed() || (controller.up.isPressed() || (controller.right.isPressed() || controller.down.isPressed()))
    if (!(moving) && Direction1 == 0 && HumanMove != 3) {
        animation.stopAnimation(animation.AnimationTypes.All, Eli)
        animation.runImageAnimation(
        Eli,
        [img`
            . . . . . . f f f f . . . . . . 
            . . . . f f e e e e f f . . . . 
            . . . f e e e f f e e e f . . . 
            . . f f f f f 2 2 f f f f f . . 
            . . f f e 2 e 2 2 e 2 e f f . . 
            . . f e 2 f 2 f f 2 f 2 e f . . 
            . . f f f 2 2 e e 2 2 f f f . . 
            . f f e f 2 f e e f 2 f e f f . 
            . f e e f f e e e e f e e e f . 
            . . f e e e e e e e e e e f . . 
            . . . f e e e e e e e e f . . . 
            . . e 4 f f f f f f f f 4 e . . 
            . . 4 d f 2 2 2 2 2 2 f d 4 . . 
            . . 4 4 f 4 4 4 4 4 4 f 4 4 . . 
            . . . . . f f f f f f . . . . . 
            . . . . . f f . . f f . . . . . 
            `],
        100,
        false
        )
    }
    if (!(moving) && Direction1 == 1 && HumanMove != 3) {
        animation.stopAnimation(animation.AnimationTypes.All, Eli)
        animation.runImageAnimation(
        Eli,
        [img`
            . . . . . . f f f f . . . . . . 
            . . . . f f f 2 2 f f f . . . . 
            . . . f f f 2 2 2 2 f f f . . . 
            . . f f f e e e e e e f f f . . 
            . . f f e 2 2 2 2 2 2 e e f . . 
            . . f e 2 f f f f f f 2 e f . . 
            . . f f f f e e e e f f f f . . 
            . f f e f b f 4 4 f b f e f f . 
            . f e e 4 1 f d d f 1 4 e e f . 
            . . f e d d d d d d d d e f . . 
            . . . f f d d d d d d f f . . . 
            . . e 4 f 2 2 2 2 2 2 f 4 e . . 
            . . 4 d f 2 2 2 2 2 2 f d 4 . . 
            . . 4 4 f 4 4 5 5 4 4 f 4 4 . . 
            . . . . . f f f f f f . . . . . 
            . . . . . f f . . f f . . . . . 
            `],
        100,
        false
        )
    }
    if (!(moving) && Direction1 == 2 && HumanMove != 3) {
        animation.stopAnimation(animation.AnimationTypes.All, Eli)
        animation.runImageAnimation(
        Eli,
        [img`
            . . . . f f f f f f . . . . . . 
            . . . f 2 f e e e e f f . . . . 
            . . f 2 2 2 f e e e e f f . . . 
            . . f e e e e f f e e e f . . . 
            . f e 2 2 2 2 e e f f f f . . . 
            . f 2 e f f f f 2 2 2 e f . . . 
            . f f f e e e f f f f f f f . . 
            . f e e 4 4 f b e 4 4 e f f . . 
            . . f e d d f 1 4 d 4 e e f . . 
            . . . f d d d d 4 e e e f . . . 
            . . . f e 4 4 4 e e f f . . . . 
            . . . f 2 2 2 e d d 4 . . . . . 
            . . . f 2 2 2 e d d e . . . . . 
            . . . f 5 5 4 f e e f . . . . . 
            . . . . f f f f f f . . . . . . 
            . . . . . . f f f . . . . . . . 
            `],
        100,
        false
        )
    }
    if (!(moving) && Direction1 == 3 && HumanMove != 3) {
        animation.stopAnimation(animation.AnimationTypes.All, Eli)
        animation.runImageAnimation(
        Eli,
        [img`
            . . . . . . f f f f f f . . . . 
            . . . . f f e e e e f 2 f . . . 
            . . . f f e e e e f 2 2 2 f . . 
            . . . f e e e f f e e e e f . . 
            . . . f f f f e e 2 2 2 2 e f . 
            . . . f e 2 2 2 f f f f e 2 f . 
            . . f f f f f f f e e e f f f . 
            . . f f e 4 4 e b f 4 4 e e f . 
            . . f e e 4 d 4 1 f d d e f . . 
            . . . f e e e 4 d d d d f . . . 
            . . . . f f e e 4 4 4 e f . . . 
            . . . . . 4 d d e 2 2 2 f . . . 
            . . . . . e d d e 2 2 2 f . . . 
            . . . . . f e e f 4 5 5 f . . . 
            . . . . . . f f f f f f . . . . 
            . . . . . . . f f f . . . . . . 
            `],
        100,
        false
        )
    }
    if (!(moving) && Direction1 == 4 && HumanMove != 3) {
        animation.stopAnimation(animation.AnimationTypes.All, Eli)
        animation.runImageAnimation(
        Eli,
        [img`
            ........................
            ........................
            ........................
            ........................
            ..........ffff..........
            ........ff1111ff........
            .......fb111111bf.......
            .......f11111111f.......
            ......fd11111111df......
            ......fd11111111df......
            ......fdd111111ddf......
            ......fbd111111dbf......
            ......fcd111111dcf......
            .......fb111111bf.......
            .....bfbfcdb1bdfbfb.....
            ....fcb1bcbfbfcb1bcf....
            ....f11111ffff11111f....
            .....ffffffffffffff.....
            .........ffffff.........
            ...........fff..........
            ........................
            ........................
            ........................
            ........................
            `],
        100,
        false
        )
    }
    if (!(moving) && Direction1 == 5 && HumanMove != 3) {
        animation.stopAnimation(animation.AnimationTypes.All, Eli)
        animation.runImageAnimation(
        Eli,
        [img`
            ........................
            ........................
            ........................
            ........................
            ..........ffff..........
            ........ff1111ff........
            .......fb111111bf.......
            .......f11111111f.......
            ......fd11111111df......
            ......fd11111111df......
            ......fddd1111dddf......
            ......fbdbfddfbdbf......
            ......fcdcf11fcdcf......
            .......fb111111bf.......
            ......fffcdb1bdffff.....
            ....fc111cbfbfc111cf....
            ....f1b1b1ffff1b1b1f....
            ....fbfbffffffbfbfbf....
            .........ffffff.........
            ...........fff..........
            ........................
            ........................
            ........................
            ........................
            `],
        100,
        false
        )
    }
    if (!(moving) && Direction1 == 6 && HumanMove != 3) {
        animation.stopAnimation(animation.AnimationTypes.All, Eli)
        animation.runImageAnimation(
        Eli,
        [img`
            ........................
            ........................
            ........................
            ........................
            ..........ffff..........
            ........ff1111ff........
            .......fb111111bf.......
            .......f1111111df.......
            ......fd1111111ddf......
            ......fd111111dddf......
            ......fd111ddddddf......
            ......fd1dfbddddbf......
            ......fbddfcdbbbcf......
            .......f11111bbcf.......
            .......f1b1fffff........
            .......fbfc111bf........
            ........ff1b1bff........
            .........fbfbfff.f......
            ..........ffffffff......
            ............fffff.......
            ........................
            ........................
            ........................
            ........................
            `],
        100,
        false
        )
    }
    if (!(moving) && Direction1 == 7 && HumanMove != 3) {
        animation.stopAnimation(animation.AnimationTypes.All, Eli)
        animation.runImageAnimation(
        Eli,
        [img`
            ........................
            ........................
            ........................
            ........................
            ..........fffff.........
            ........ff11111f........
            .......fb111111bf.......
            ......fbd1111111f.......
            ......fddd111111df......
            ......fdddd11111df......
            ......fddddddd11df......
            ......fddddddd111f......
            ......fddddddcf11f......
            .......fbdddb1111bf.....
            ........fffcfdb1b1f.....
            .......ffffffffbfbf.....
            ....ff.fffffffffff......
            .....ffffffff...........
            .....ffffffb1b1f........
            ......ffffffbfbf........
            ........................
            ........................
            ........................
            ........................
            `],
        100,
        false
        )
    }
}
controller.left.onEvent(ControllerButtonEvent.Pressed, function () {
    if (HumanMove == 1) {
        animation.runImageAnimation(
        Eli,
        [img`
            . . . . f f f f f f . . . . . . 
            . . . f 2 f e e e e f f . . . . 
            . . f 2 2 2 f e e e e f f . . . 
            . . f e e e e f f e e e f . . . 
            . f e 2 2 2 2 e e f f f f . . . 
            . f 2 e f f f f 2 2 2 e f . . . 
            . f f f e e e f f f f f f f . . 
            . f e e 4 4 f b e 4 4 e f f . . 
            . . f e d d f 1 4 d 4 e e f . . 
            . . . f d d d d 4 e e e f . . . 
            . . . f e 4 4 4 e e f f . . . . 
            . . . f 2 2 2 e d d 4 . . . . . 
            . . . f 2 2 2 e d d e . . . . . 
            . . . f 5 5 4 f e e f . . . . . 
            . . . . f f f f f f . . . . . . 
            . . . . . . f f f . . . . . . . 
            `,img`
            . . . . . . . . . . . . . . . . 
            . . . . f f f f f f . . . . . . 
            . . . f 2 f e e e e f f . . . . 
            . . f 2 2 2 f e e e e f f . . . 
            . . f e e e e f f e e e f . . . 
            . f e 2 2 2 2 e e f f f f . . . 
            . f 2 e f f f f 2 2 2 e f . . . 
            . f f f e e e f f f f f f f . . 
            . f e e 4 4 f b e 4 4 e f f . . 
            . . f e d d f 1 4 d 4 e e f . . 
            . . . f d d d e e e e e f . . . 
            . . . f e 4 e d d 4 f . . . . . 
            . . . f 2 2 e d d e f . . . . . 
            . . f f 5 5 f e e f f f . . . . 
            . . f f f f f f f f f f . . . . 
            . . . f f f . . . f f . . . . . 
            `,img`
            . . . . f f f f f f . . . . . . 
            . . . f 2 f e e e e f f . . . . 
            . . f 2 2 2 f e e e e f f . . . 
            . . f e e e e f f e e e f . . . 
            . f e 2 2 2 2 e e f f f f . . . 
            . f 2 e f f f f 2 2 2 e f . . . 
            . f f f e e e f f f f f f f . . 
            . f e e 4 4 f b e 4 4 e f f . . 
            . . f e d d f 1 4 d 4 e e f . . 
            . . . f d d d d 4 e e e f . . . 
            . . . f e 4 4 4 e e f f . . . . 
            . . . f 2 2 2 e d d 4 . . . . . 
            . . . f 2 2 2 e d d e . . . . . 
            . . . f 5 5 4 f e e f . . . . . 
            . . . . f f f f f f . . . . . . 
            . . . . . . f f f . . . . . . . 
            `,img`
            . . . . . . . . . . . . . . . . 
            . . . . f f f f f f . . . . . . 
            . . . f 2 f e e e e f f . . . . 
            . . f 2 2 2 f e e e e f f . . . 
            . . f e e e e f f e e e f . . . 
            . f e 2 2 2 2 e e f f f f . . . 
            . f 2 e f f f f 2 2 2 e f . . . 
            . f f f e e e f f f f f f f . . 
            . f e e 4 4 f b e 4 4 e f f . . 
            . . f e d d f 1 4 d 4 e e f . . 
            . . . f d d d d 4 e e e f . . . 
            . . . f e 4 4 4 e d d 4 . . . . 
            . . . f 2 2 2 2 e d d e . . . . 
            . . f f 5 5 4 4 f e e f . . . . 
            . . f f f f f f f f f f . . . . 
            . . . f f f . . . f f . . . . . 
            `],
        100,
        true
        )
        Direction1 = 2
    }
    if (HumanMove == 2) {
        animation.runImageAnimation(
        Eli,
        [img`
            ........................
            ........................
            ........................
            ........................
            ..........ffff..........
            ........ff1111ff........
            .......fb111111bf.......
            .......f1111111df.......
            ......fd1111111ddf......
            ......fd111111dddf......
            ......fd111ddddddf......
            ......fd1dfbddddbf......
            ......fbddfcdbbbcf......
            .......f11111bbcf.......
            .......f1b1fffff........
            .......fbfc111bf........
            ........ff1b1bff........
            .........fbfbfff.f......
            ..........ffffffff......
            ............fffff.......
            ........................
            ........................
            ........................
            ........................
            `,img`
            ........................
            ........................
            ........................
            ........................
            .........fffff..........
            ........f11111ff........
            .......fb111111bf.......
            .......f1111111dbf......
            ......fd111111dddf......
            ......fd11111ddddf......
            ......fd11dddddddf......
            ......f111dddddddf......
            ......f11fcddddddf......
            .....fb1111bdddbf.......
            .....f1b1bdfcfff........
            .....fbfbffffffff.......
            ......fffffffffff.ff....
            ...........ffffffff.....
            ........f1b1bffffff.....
            ........fbfbffffff......
            ........................
            ........................
            ........................
            ........................
            `],
        100,
        true
        )
        Direction1 = 6
    }
})
sprites.onOverlap(SpriteKind.Player, SpriteKind.Entity, function (sprite, otherSprite) {
    MusicCounter = 2
    sprites.destroy(MysteriousEntity, effects.ashes, 100)
    HumanMove = 3
    animation.runImageAnimation(
    Eli,
    [img`
        ......ffff..............
        ....fff22fff............
        ...fff2222fff...........
        ..fffeeeeeefff..........
        ..ffe222222eef..........
        ..fe2ffffff2ef..........
        ..ffffeeeeffff..........
        .ffefbf44fbfeff.........
        .fee41fddf14eef.........
        ..feeddddddeef..........
        ...fee4444eef...........
        ..e4f222222f4e..........
        ..4df222222fd4..........
        ..44f445544f44..........
        .....ffffff.............
        .....ff..ff.............
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        `,img`
        ......1111..............
        ....11122111............
        ...11f2222f11...........
        ..11feeeeeef11..........
        ..1fe222222ee1..........
        ..1e2ffffff2e1..........
        ..1fffeeeefff1..........
        .11efbf44fbfe11.........
        .11e41fddf14e11.........
        ..11edddddde11..........
        ...1ee4444ee1...........
        ..11f222222f11..........
        ..111222222111..........
        ..111445544111..........
        .....111111.............
        .....11..11.............
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        `,img`
        ......1111..............
        ....11111111............
        ...1111111111...........
        ..111111111111..........
        ..111222222111..........
        ..111ffffff111..........
        ..111feeeef111..........
        .111fbf44fbf111.........
        .11141fddf14111.........
        ..111dddddd111..........
        ...1111111111...........
        ..111111111111..........
        ..111111111111..........
        ..111111111111..........
        .....111111.............
        .....11..11.............
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        `,img`
        ......1111..............
        ....11111111............
        ...1111111111...........
        ..111111111111..........
        ..111111111111..........
        ..111111111111..........
        ..111111111111..........
        .11111111111111.........
        .11111111111111.........
        ..111111111111..........
        ...1111111111...........
        ..111111111111..........
        ..111111111111..........
        ..111111111111..........
        .....111111.............
        .....11..11.............
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        `,img`
        ........................
        ........................
        ........................
        ........................
        ..........ffff..........
        ........ff1111ff........
        .......fb111111bf.......
        .......f11111111f.......
        ......fd11111111df......
        ......fd11111111df......
        ......fddd1111dddf......
        ......fbdbfddfbdbf......
        ......fcdcf11fcdcf......
        .......fb111111bf.......
        ......fffcdb1bdffff.....
        ....fc111cbfbfc111cf....
        ....f1b1b1ffff1b1b1f....
        ....fbfbffffffbfbfbf....
        .........ffffff.........
        ...........fff..........
        ........................
        ........................
        ........................
        ........................
        `],
    200,
    false
    )
    timer.after(500, function () {
        tiles.setCurrentTilemap(tilemap`level5`)
        tiles.placeOnTile(Eli, tiles.getTileLocation(1, 1))
        HumanMove = 2
        timer.after(500, function () {
            tiles.setCurrentTilemap(tilemap`level4`)
        })
    })
    Orb = sprites.create(img`
        . . . . . . . . . . . . . . . . 
        . . . . . . 6 6 6 6 . . . . . . 
        . . . . 6 6 6 5 5 6 6 6 . . . . 
        . . . 7 7 7 7 6 6 6 6 6 6 . . . 
        . . 6 7 7 7 7 8 8 8 1 1 6 6 . . 
        . . 7 7 7 7 7 8 8 8 1 1 5 6 . . 
        . 6 7 7 7 7 8 8 8 8 8 5 5 6 6 . 
        . 6 7 7 7 8 8 8 6 6 6 6 5 6 6 . 
        . 6 6 7 7 8 8 6 6 6 6 6 6 6 6 . 
        . 6 8 7 7 8 8 6 6 6 6 6 6 6 6 . 
        . . 6 8 7 7 8 6 6 6 6 6 8 6 . . 
        . . 6 8 8 7 8 8 6 6 6 8 6 6 . . 
        . . . 6 8 8 8 8 8 8 8 8 6 . . . 
        . . . . 6 6 8 8 8 8 6 6 . . . . 
        . . . . . . 6 6 6 6 . . . . . . 
        . . . . . . . . . . . . . . . . 
        `, SpriteKind.Food)
    tiles.placeOnTile(Orb, tiles.getTileLocation(1, 26))
})
controller.right.onEvent(ControllerButtonEvent.Pressed, function () {
    if (HumanMove == 1) {
        animation.runImageAnimation(
        Eli,
        [img`
            . . . . . . f f f f f f . . . . 
            . . . . f f e e e e f 2 f . . . 
            . . . f f e e e e f 2 2 2 f . . 
            . . . f e e e f f e e e e f . . 
            . . . f f f f e e 2 2 2 2 e f . 
            . . . f e 2 2 2 f f f f e 2 f . 
            . . f f f f f f f e e e f f f . 
            . . f f e 4 4 e b f 4 4 e e f . 
            . . f e e 4 d 4 1 f d d e f . . 
            . . . f e e e 4 d d d d f . . . 
            . . . . f f e e 4 4 4 e f . . . 
            . . . . . 4 d d e 2 2 2 f . . . 
            . . . . . e d d e 2 2 2 f . . . 
            . . . . . f e e f 4 5 5 f . . . 
            . . . . . . f f f f f f . . . . 
            . . . . . . . f f f . . . . . . 
            `,img`
            . . . . . . . . . . . . . . . . 
            . . . . . . f f f f f f . . . . 
            . . . . f f e e e e f 2 f . . . 
            . . . f f e e e e f 2 2 2 f . . 
            . . . f e e e f f e e e e f . . 
            . . . f f f f e e 2 2 2 2 e f . 
            . . . f e 2 2 2 f f f f e 2 f . 
            . . f f f f f f f e e e f f f . 
            . . f f e 4 4 e b f 4 4 e e f . 
            . . f e e 4 d 4 1 f d d e f . . 
            . . . f e e e e e d d d f . . . 
            . . . . . f 4 d d e 4 e f . . . 
            . . . . . f e d d e 2 2 f . . . 
            . . . . f f f e e f 5 5 f f . . 
            . . . . f f f f f f f f f f . . 
            . . . . . f f . . . f f f . . . 
            `,img`
            . . . . . . f f f f f f . . . . 
            . . . . f f e e e e f 2 f . . . 
            . . . f f e e e e f 2 2 2 f . . 
            . . . f e e e f f e e e e f . . 
            . . . f f f f e e 2 2 2 2 e f . 
            . . . f e 2 2 2 f f f f e 2 f . 
            . . f f f f f f f e e e f f f . 
            . . f f e 4 4 e b f 4 4 e e f . 
            . . f e e 4 d 4 1 f d d e f . . 
            . . . f e e e 4 d d d d f . . . 
            . . . . f f e e 4 4 4 e f . . . 
            . . . . . 4 d d e 2 2 2 f . . . 
            . . . . . e d d e 2 2 2 f . . . 
            . . . . . f e e f 4 5 5 f . . . 
            . . . . . . f f f f f f . . . . 
            . . . . . . . f f f . . . . . . 
            `,img`
            . . . . . . . . . . . . . . . . 
            . . . . . . f f f f f f . . . . 
            . . . . f f e e e e f 2 f . . . 
            . . . f f e e e e f 2 2 2 f . . 
            . . . f e e e f f e e e e f . . 
            . . . f f f f e e 2 2 2 2 e f . 
            . . . f e 2 2 2 f f f f e 2 f . 
            . . f f f f f f f e e e f f f . 
            . . f f e 4 4 e b f 4 4 e e f . 
            . . f e e 4 d 4 1 f d d e f . . 
            . . . f e e e 4 d d d d f . . . 
            . . . . 4 d d e 4 4 4 e f . . . 
            . . . . e d d e 2 2 2 2 f . . . 
            . . . . f e e f 4 4 5 5 f f . . 
            . . . . f f f f f f f f f f . . 
            . . . . . f f . . . f f f . . . 
            `],
        100,
        true
        )
        Direction1 = 3
    }
    if (HumanMove == 2) {
        animation.runImageAnimation(
        Eli,
        [img`
            ........................
            ........................
            ........................
            ........................
            ..........fffff.........
            ........ff11111f........
            .......fb111111bf.......
            ......fbd1111111f.......
            ......fddd111111df......
            ......fdddd11111df......
            ......fddddddd11df......
            ......fddddddd111f......
            ......fddddddcf11f......
            .......fbdddb1111bf.....
            ........fffcfdb1b1f.....
            .......ffffffffbfbf.....
            ....ff.fffffffffff......
            .....ffffffff...........
            .....ffffffb1b1f........
            ......ffffffbfbf........
            ........................
            ........................
            ........................
            ........................
            `,img`
            ........................
            ........................
            ........................
            ........................
            ..........ffff..........
            ........ff1111ff........
            .......fb111111bf.......
            .......fd1111111f.......
            ......fdd1111111df......
            ......fddd111111df......
            ......fdddddd111df......
            ......fbddddbfd1df......
            ......fcbbbdcfddbf......
            .......fcbb11111f.......
            ........fffff1b1f.......
            ........fb111cfbf.......
            ........ffb1b1ff........
            ......f.fffbfbf.........
            ......ffffffff..........
            .......fffff............
            ........................
            ........................
            ........................
            ........................
            `],
        100,
        true
        )
        Direction1 = 7
    }
})
controller.down.onEvent(ControllerButtonEvent.Pressed, function () {
    if (HumanMove == 1) {
        animation.runImageAnimation(
        Eli,
        [img`
            . . . . . . f f f f . . . . . . 
            . . . . f f f 2 2 f f f . . . . 
            . . . f f f 2 2 2 2 f f f . . . 
            . . f f f e e e e e e f f f . . 
            . . f f e 2 2 2 2 2 2 e e f . . 
            . . f e 2 f f f f f f 2 e f . . 
            . . f f f f e e e e f f f f . . 
            . f f e f b f 4 4 f b f e f f . 
            . f e e 4 1 f d d f 1 4 e e f . 
            . . f e d d d d d d d d e f . . 
            . . . f f d d d d d d f f . . . 
            . . e 4 f 2 2 2 2 2 2 f 4 e . . 
            . . 4 d f 2 2 2 2 2 2 f d 4 . . 
            . . 4 4 f 4 4 5 5 4 4 f 4 4 . . 
            . . . . . f f f f f f . . . . . 
            . . . . . f f . . f f . . . . . 
            `,img`
            . . . . . . . . . . . . . . . . 
            . . . . . . f f f f . . . . . . 
            . . . . f f f 2 2 f f f . . . . 
            . . . f f f 2 2 2 2 f f f . . . 
            . . f f f e e e e e e f f f . . 
            . . f f e 2 2 2 2 2 2 e e f . . 
            . f f e 2 f f f f f f 2 e f f . 
            . f f f f f e e e e f f f f f . 
            . . f e f b f 4 4 f b f e f . . 
            . . f e 4 1 f d d f 1 4 e f . . 
            . . f f e 4 d d d d 4 e f e . . 
            . . d e f 2 2 2 2 e d d 4 e . . 
            . . d 4 f 2 2 2 2 e d d e . . . 
            . . . . f 4 4 5 5 f e e . . . . 
            . . . . f f f f f f f . . . . . 
            . . . . f f f . . . . . . . . . 
            `,img`
            . . . . . . . . . . . . . . . . 
            . . . . . . f f f f . . . . . . 
            . . . . f f f 2 2 f f f . . . . 
            . . . f f f 2 2 2 2 f f f . . . 
            . . f f f e e e e e e f f f . . 
            . . f e e 2 2 2 2 2 2 e f f . . 
            . f f e 2 f f f f f f 2 e f f . 
            . f f f f f e e e e f f f f f . 
            . . f e f b f 4 4 f b f e f . . 
            . . f e 4 1 f d d f 1 4 e f . . 
            . . e f e 4 d d d d 4 e f f . . 
            . . e 4 d d e 2 2 2 2 f e d . . 
            . . . e d d e 2 2 2 2 f 4 d . . 
            . . . . e e f 5 5 4 4 f . . . . 
            . . . . . f f f f f f f . . . . 
            . . . . . . . . . f f f . . . . 
            `,img`
            . . . . . . . . . . . . . . . . 
            . . . . . . f f f f . . . . . . 
            . . . . f f f 2 2 f f f . . . . 
            . . . f f f 2 2 2 2 f f f . . . 
            . . f f f e e e e e e f f f . . 
            . . f e e 2 2 2 2 2 2 e f f . . 
            . f f e 2 f f f f f f 2 e f f . 
            . f f f f f e e e e f f f f f . 
            . . f e f b f 4 4 f b f e f . . 
            . . f e 4 1 f d d f 1 4 e f . . 
            . . e f e 4 d d d d 4 e f . . . 
            . . e 4 d d e 2 2 2 2 f e d . . 
            . . . e d d e 2 2 2 2 f 4 d . . 
            . . . . e e f 5 5 4 4 f . . . . 
            . . . . . f f f f f f f . . . . 
            . . . . . . . . . f f f . . . . 
            `],
        100,
        true
        )
        Direction1 = 1
    }
    if (HumanMove == 2) {
        animation.runImageAnimation(
        Eli,
        [img`
            ........................
            ........................
            ........................
            ........................
            ..........ffff..........
            ........ff1111ff........
            .......fb111111bf.......
            .......f11111111f.......
            ......fd11111111df......
            ......fd11111111df......
            ......fddd1111dddf......
            ......fbdbfddfbdbf......
            ......fcdcf11fcdcf......
            .......fb111111bf.......
            ......fffcdb1bdffff.....
            ....fc111cbfbfc111cf....
            ....f1b1b1ffff1b1b1f....
            ....fbfbffffffbfbfbf....
            .........ffffff.........
            ...........fff..........
            ........................
            ........................
            ........................
            ........................
            `,img`
            ........................
            ........................
            ........................
            ........................
            ..........ffff..........
            ........ff1111ff........
            .......fb111111bf.......
            .......f11111111f.......
            ......fd11111111df......
            ......fd11111111df......
            ......fddd1111dddf......
            ......fbdbfddfbdbf......
            ......fcdcf11fcdcf......
            .......fb111111ffff.....
            ......fffcdb1bc111cf....
            ....fc111cbfbf1b1b1f....
            ....f1b1b1ffffbfbfbf....
            ....fbfbfffffff.........
            .........fffff..........
            ..........fff...........
            ........................
            ........................
            ........................
            ........................
            `,img`
            ........................
            ........................
            ........................
            ........................
            ..........ffff..........
            ........ff1111ff........
            .......fb111111bf.......
            .......f11111111f.......
            ......fd11111111df......
            ......fd11111111df......
            ......fddd1111dddf......
            ......fbdbfddfbdbf......
            ......fcdcf11fcdcf......
            .......fb111111bf.......
            ......fffcdb1bdffff.....
            ....fc111cbfbfc111cf....
            ....f1b1b1ffff1b1b1f....
            ....fbfbffffffbfbfbf....
            .........ffffff.........
            ...........fff..........
            ........................
            ........................
            ........................
            ........................
            `,img`
            ........................
            ........................
            ........................
            ........................
            ..........ffff..........
            ........ff1111ff........
            .......fb111111bf.......
            .......f11111111f.......
            ......fd11111111df......
            ......fd11111111df......
            ......fddd1111dddf......
            ......fbdbfddfbdbf......
            ......fcdcf11fcdcf......
            .....ffff111111bf.......
            ....fc111cdb1bdfff......
            ....f1b1bcbfbfc111cf....
            ....fbfbfbffff1b1b1f....
            .........fffffffbfbf....
            ..........fffff.........
            ...........fff..........
            ........................
            ........................
            ........................
            ........................
            `],
        100,
        true
        )
        Direction1 = 5
    }
})
sprites.onOverlap(SpriteKind.Player, SpriteKind.Food, function (sprite, otherSprite) {
    sprites.destroy(otherSprite, effects.disintegrate, 500)
    ScratchAttack = 1
    can_attack = 0
    MysteriousEntity2 = sprites.create(img`
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . f f f f f f f f . . . . 
        . . . f f f f f f f f f f . . . 
        . . . f f f f f f f f f f . . . 
        . . . f f 1 1 f f 1 1 f f . . . 
        . . . f f 1 1 f f 1 1 f f . . . 
        . . . f f 2 f f f f 2 f f . . . 
        . . . f f 2 f f f f 2 f f . . . 
        . . . . . f f f f f f . . . . . 
        . . f f f f f f f f f f f f . . 
        . . f f f f f f f f f f f f . . 
        . . f f f f f f f f f f f f . . 
        . . . . . f f f f f f . . . . . 
        . . . . . f f . . f f . . . . . 
        `, SpriteKind.Entity2)
    tiles.placeOnTile(MysteriousEntity2, tiles.getTileLocation(1, 22))
})
let MysteriousEntity2: Sprite = null
let Orb: Sprite = null
let moving = false
let can_attack = 0
let ScratchAttack = 0
let Direction1 = 0
let FamiliarEntity: Sprite = null
let MusicCounter = 0
let MysteriousEntity: Sprite = null
let HumanMove = 0
let Eli: Sprite = null
Eli = sprites.create(img`
    . . . . . . f f f f . . . . . . 
    . . . . f f f 2 2 f f f . . . . 
    . . . f f f 2 2 2 2 f f f . . . 
    . . f f f e e e e e e f f f . . 
    . . f f e 2 2 2 2 2 2 e e f . . 
    . . f e 2 f f f f f f 2 e f . . 
    . . f f f f e e e e f f f f . . 
    . f f e f b f 4 4 f b f e f f . 
    . f e e 4 1 f d d f 1 4 e e f . 
    . . f e e d d d d d d e e f . . 
    . . . f e e 4 4 4 4 e e f . . . 
    . . e 4 f 2 2 2 2 2 2 f 4 e . . 
    . . 4 d f 2 2 2 2 2 2 f d 4 . . 
    . . 4 4 f 4 4 5 5 4 4 f 4 4 . . 
    . . . . . f f f f f f . . . . . 
    . . . . . f f . . f f . . . . . 
    `, SpriteKind.Player)
HumanMove = 1
MysteriousEntity = sprites.create(img`
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . f f f f f f f f . . . . 
    . . . f f f f f f f f f f . . . 
    . . . f f f f f f f f f f . . . 
    . . . f f 1 1 f f 1 1 f f . . . 
    . . . f f 1 1 f f 1 1 f f . . . 
    . . . f f 9 f f f f 9 f f . . . 
    . . . f f 9 f f f f 9 f f . . . 
    . . . . . f f f f f f . . . . . 
    . . f f f f f f f f f f f f . . 
    . . f f f f f f f f f f f f . . 
    . . f f f f f f f f f f f f . . 
    . . . . . f f f f f f . . . . . 
    . . . . . f f . . f f . . . . . 
    `, SpriteKind.Entity)
scene.cameraFollowSprite(Eli)
controller.moveSprite(Eli)
tiles.setCurrentTilemap(tilemap`level1`)
tiles.placeOnTile(MysteriousEntity, tiles.getTileLocation(4, 13))
MusicCounter = 1
game.onUpdate(function () {
    Animation()
})
